name: Plugin#1
version: 1.0.0
api: 3.21.1
main: LunarMoon72\Plugin#1\Main
author: LunarMoon72
mcpe-protocal: 448

commands:
  food:
    description: Give yourself Food!
  heal:
    description: Heal yourself!
  testmessage:
    description: test message
